language: ruby
rvm: 2.5.1
addons:
  ssh_known_hosts:
    - 93.185.103.119:2222
before_install:
  - openssl aes-256-cbc -K $encrypted_dc982276292c_key -iv $encrypted_dc982276292c_iv
    -in deploy_rsa_sandbox.enc -out /tmp/deploy_rsa_sandbox -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa_sandbox
  - ssh-add /tmp/deploy_rsa_sandbox
  - gem install bundler
  - nvm install node
  - npm install -g gulp-cli
before_script:
  - npm install
script:
  - npm run build:production
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet -e 'ssh -p 2222' $TRAVIS_BUILD_DIR/_site piratipardubice@93.185.103.119:/srv/pirati-tmp
  on:
    branch: master
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
