language: ruby
rvm: 2.5.1

before_install:
  - gem install bundler
  - nvm install node
  - npm install -g gulp-cli

before_script:
  - npm install

script:
  - npm run build:production

branches:
  only:
    - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
